<h1><b>Pandas :--- panell data </b></h1>

<h2>Creating series </h2>

In [3]:
import numpy as np
import pandas as pd

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ayush\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ayush\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\ayush\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------- ----------------- 5.5/9.8 MB 30.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 24.4 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 22.5 MB/s eta 0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.3 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
labels = ['a', 'b', 'c']
my_list=[10, 20, 30]
s = pd.Series(my_list, index=labels)
s

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
#passing the dictonary
d={1:10,2:20,3:30}
pd.Series(d)

1    10
2    20
3    30
dtype: int64

<h2>Dataframes</h2>

when we combine multiple series into a single frame called <b>dataframe</b>

In [8]:
data={
    'name':['john','anna','peter','linda'],
    'age':[34,21,19,20],
    'city':['new york','paris','berlin','london'],
    'salary':[25000,32000,12500,18000]
}

df= pd.DataFrame(data)

In [9]:
df

    name  age      city  salary
0   john   34  new york   25000
1   anna   21     paris   32000
2  peter   19    berlin   12500
3  linda   20    london   18000

<h2>Selection and indexing</h2>

In [10]:
df.city

0    new york
1       paris
2      berlin
3      london
Name: city, dtype: str

In [11]:
df['city']

0    new york
1       paris
2      berlin
3      london
Name: city, dtype: str

In [12]:
df[['name','city']]

    name      city
0   john  new york
1   anna     paris
2  peter    berlin
3  linda    london

<h2> Creating a new column </h2>

In [13]:
df['Designation'] = ['Manager','Team Lead','Developer','Intern']
df

    name  age      city  salary Designation
0   john   34  new york   25000     Manager
1   anna   21     paris   32000   Team Lead
2  peter   19    berlin   12500   Developer
3  linda   20    london   18000      Intern

<h2>deleting or drop a cloumn </h2>

In [14]:
df.drop('Designation', axis=1)

    name  age      city  salary
0   john   34  new york   25000
1   anna   21     paris   32000
2  peter   19    berlin   12500
3  linda   20    london   18000

In [15]:
df

    name  age      city  salary Designation
0   john   34  new york   25000     Manager
1   anna   21     paris   32000   Team Lead
2  peter   19    berlin   12500   Developer
3  linda   20    london   18000      Intern

here with the drop statement if we want to permanent Delete we have to use <b>inplace= true</b><br>
df.drop('Designation', axis=1, inplace=true)

<h2>Removing a row</h2>

In [16]:
df.drop(0,axis=0)

    name  age    city  salary Designation
1   anna   21   paris   32000   Team Lead
2  peter   19  berlin   12500   Developer
3  linda   20  london   18000      Intern

<h2> Selecting a Row<h2>

In [17]:
df.loc[[0,1]]

   name  age      city  salary Designation
0  john   34  new york   25000     Manager
1  anna   21     paris   32000   Team Lead

In [18]:
df.loc[0]

name               john
age                  34
city           new york
salary            25000
Designation     Manager
Name: 0, dtype: object

using the index <b>iloc</h2>

In [19]:
df.iloc[3]

name            linda
age                20
city           london
salary          18000
Designation    Intern
Name: 3, dtype: object

<h2>Selecting  subset of the rows and column </h2>

In [20]:
df.loc[[0,1],['name','salary']]

   name  salary
0  john   25000
1  anna   32000

<h2><b>Conditional selection:--- </b></h2>

In [21]:
#want to select those people whose age is greater than 20
df[df['age']>20]

   name  age      city  salary Designation
0  john   34  new york   25000     Manager
1  anna   21     paris   32000   Team Lead

In [22]:
df[(df['age']>20) & (df['salary']>25000)]

   name  age   city  salary Designation
1  anna   21  paris   32000   Team Lead

<h2>Missing data </h2>

In [23]:
data2={
    'A':[1,2,np.nan],
    'B':[5,np.nan,np.nan],
    'C':[1,2,3],
    'D':[4,5,6]
}
df2= pd.DataFrame(data2)

In [24]:
df2

     A    B  C  D
0  1.0  5.0  1  4
1  2.0  NaN  2  5
2  NaN  NaN  3  6

checking the null values presentbor not

In [26]:
df2.isna()

       A      B      C      D
0  False  False  False  False
1  False   True  False  False
2   True   True  False  False

In [27]:
df.isna().sum()

name           0
age            0
city           0
salary         0
Designation    0
dtype: int64

In [28]:
df2.isna().sum()

A    1
B    2
C    0
D    0
dtype: int64

In [29]:
#to check the value are other than the null values
df2.isna().any()

A     True
B     True
C    False
D    False
dtype: bool

<h2>Removing the missing values</h2>

In [30]:
df2.dropna()

     A    B  C  D
0  1.0  5.0  1  4

In [31]:
df2

     A    B  C  D
0  1.0  5.0  1  4
1  2.0  NaN  2  5
2  NaN  NaN  3  6

In [33]:
#removing the rows where non null values are at least =3
df2.dropna(thresh=3)

     A    B  C  D
0  1.0  5.0  1  4
1  2.0  NaN  2  5

filling missing data

In [34]:
df.fillna(0)

    name  age      city  salary Designation
0   john   34  new york   25000     Manager
1   anna   21     paris   32000   Team Lead
2  peter   19    berlin   12500   Developer
3  linda   20    london   18000      Intern

In [35]:
df2.fillna(0)

     A    B  C  D
0  1.0  5.0  1  4
1  2.0  0.0  2  5
2  0.0  0.0  3  6

In [36]:
#fillling missing values with the specfic values
values={'A':0,'B':1,'C':2,'D':3}
df2.fillna(value=values)

     A    B  C  D
0  1.0  5.0  1  4
1  2.0  1.0  2  5
2  0.0  1.0  3  6

In [37]:
#filling null values with mean values
df2.fillna(df2.mean())

     A    B  C  D
0  1.0  5.0  1  4
1  2.0  5.0  2  5
2  1.5  5.0  3  6

<h2>Merging joining concatination</h2>

In [38]:
employees=pd.DataFrame({
    'employee_id':[1,2,3,4],
    'employee_name':['john','anna','peter','linda'],
    'department':['IT','HR','Finance','Marketing']
})

#dataFrame 2

salaries=pd.DataFrame({
    'employee_id':[1,2,3,6],
    'salary':[25000,32000,12500,18000],
    'bonus':[5000,7000,2000,3000]
})

In [39]:
employees

   employee_id employee_name department
0            1          john         IT
1            2          anna         HR
2            3         peter    Finance
3            4         linda  Marketing

In [40]:
salaries

   employee_id  salary  bonus
0            1   25000   5000
1            2   32000   7000
2            3   12500   2000
3            6   18000   3000

In [41]:
pd.merge(employees,salaries,on='employee_id')

   employee_id employee_name department  salary  bonus
0            1          john         IT   25000   5000
1            2          anna         HR   32000   7000
2            3         peter    Finance   12500   2000

In [42]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id employee_name department   salary   bonus
0            1          john         IT  25000.0  5000.0
1            2          anna         HR  32000.0  7000.0
2            3         peter    Finance  12500.0  2000.0
3            4         linda  Marketing      NaN     NaN
4            6           NaN        NaN  18000.0  3000.0

<h2>Concatination of 2 dataframe</h2>

In [43]:
df3=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})

df4=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [44]:
df3

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [45]:
df4

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [46]:
pd.concat([df3,df4])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [47]:
pd.concat([df3,df4] ,axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

<h2>Joining 2 dataframes</h2>

In [48]:
df5=pd.DataFrame({
    'name':['john','anna','peter','linda'],
    'index':[1,2,3,4]
})
#second dataframe
df6= pd.DataFrame({
    'score':[85,90,78,92],
    'index':[2,3,4,5]
})

In [49]:
df5

    name  index
0   john      1
1   anna      2
2  peter      3
3  linda      4

In [50]:
df6

   score  index
0     85      2
1     90      3
2     78      4
3     92      5

In [59]:
df5.merge(df6, on="index", how="inner")

    name  index  score
0   anna      2     85
1  peter      3     90
2  linda      4     78